# Should Xperms save new users to users.yml when they join?
SaveUsersOnJoin: true

CheckUpdate:
  OnStart: true
  OnJoin: true

# Rank ladder lists, ordered from lowest rank to highest:
ladders:
  SampleLadder:
  - Default
  - Mod
  - Admin
  - Owner

# Don't touch this. Seriously. It will break things.
ConfigVersion: 2.2